#import "../../lib.typ": alpha-enum, ex
#import "@preview/cetz:0.5.2"

#let int = math.op("int")

== Exercise 2.9 (Voronoi sets and polyhedral decomposition)

#ex[
  Let $x_0, dots, x_K in RR^n$ be distinct. Consider the set of points that are
  closer (in Euclidean norm) to $x_0$ than the other $x_i$, i.e.,

  $ V = { x in RR^n mid(|) norm(x - x_0)_2 <= norm(x - x_i)_2, i = 1, dots, K }. $

  $V$ is called the Voronoi region around $x_0$ with respect to $x_1, dots, x_K$.

  #alpha-enum(
    [
      Show that $V$ is a polyhedron. Express $V$ in the form $V = { x mid(|) A x prec.eq b }$.
    ],
    [
      Conversely, given a polyhedron $P$ with nonempty interior, show how to find
      $x_0, dots, x_K$ so that the polyhedron is the Voronoi region of $x_0$ with
      respect to $x_1, dots, x_K$.
    ],
    [
      We can also consider the sets

      $ V_k = { x in RR^n mid(|) norm(x - x_k)_2 <= norm(x - x_i)_2, i eq.not k }. $

      The set $V_k$ consists of points in $RR^n$ for which the closest point in the
      set ${x_0, dots, x_K}$ is $x_k$. \
      The sets $V_0, dots, V_K$ give a #emph[polyhedral decomposition] of $RR^n$.
      More precisely, the sets $V_k$ are polyhedra with nonempty interior,
      $union.big_(k=0)^K V_k = RR^n$, and $"int" V_i inter "int" V_j = nothing$ for
      $i eq.not j$, i.e., $V_i$ and $V_j$ intersect at most along a boundary. \
      Suppose that $P_1, dots, P_m$ are polyhedra with nonempty interior such that
      $union.big_(i=1)^m P_i = RR^n$, $"int" P_i inter "int" P_j = nothing$ for
      $i eq.not j$. Can this polyhedral decomposition of $RR^n$ be described as the
      Voronoi regions generated by an appropriate set of points?
    ],
  )
]

*解答*:
#alpha-enum(
  [
    $A in RR^(K times n)$ と $b in RR^K$ を次のように定める.

    $
      A = mat((x_1 - x_0)^T; dots.v; (x_K - x_0)^T), quad b = mat((norm(x_1)_2^2 - norm(x_0)_2^2) / 2; dots.v; (norm(x_K)_2^2 - norm(x_0)_2^2) / 2)
    $

    このとき #link(<ex-2-7>)[演習問題 2.7] より

    $
      { x mid(|) A x prec.eq b } = { x in RR^n mid(|) norm(x - x_0)_2 <= norm(x - x_i)_2, i = 1, dots, K } = V
    $

    である.
  ],
  [
    $P$ は内部を持つため $P = { x in RR^n mid(|) A x prec.eq b}$ と書ける ($A in RR^(K times n)$, $b in RR^K$).
    $A$ の $i$ 行目を $a_i^T$ とおく.
    ここで $A$ は全ての成分が $0$ の行を持たないとする. つまり $a_i eq.not 0$ である.
    $x_0 in int P$ を取る. このとき $A x_0 prec b$ が成り立つ.
    $t_i$ と $x_i$ を以下のように定める.

    $
      t_i := (b_i - a_i^T x_0) / norm(a_i)_2^2, quad x_i := x_0 + 2 t_i a_i
    $

    ここで $x_i$ は超平面 $a_i x = b_i$ における $x_0$ の鏡映となっている.
    また, $t_i > 0$ であることに注意する.
    このとき

    $
      a_i^T y <= b_i & <=> 2 t_i a_i^T y <= 2 t_i b_i \
                     & <=> (x_i - x_0)^T y <= 2 t_i (t_i norm(a_i)_2^2 + a_i^T x_0) \
                     & <=> (x_i - x_0)^T y <= 1/2 (4 norm(t_i a_i)_2^2 + 4 t_i a_i^T x_0) \
                     & <=> (x_i - x_0)^T y <= (norm(x_i)_2^2 - norm(x_0)_2^2)/2.
    $

    従って $P$ は $x_1, dots, x_K$ に対する $x_0$ の Voronoi region である.
  ],
  [
    一般には成り立たない. $RR^2$ 内で反例を示す. 以下のように置く.
    $
      P_1 = {mat(x; y) in RR^2 mid(|) y >= 0}
      , quad P_2 = {mat(x; y) in RR^2 mid(|) x <= 0, y <= 0}
      , quad P_3 = {mat(x; y) in RR^2 mid(|) x >= 0, y <= 0}
    $

    #let non-voronoi = cetz.canvas(length: 1cm, {
      import cetz.draw: *
      let ink = rgb(130, 130, 130)
      let region(a, b, pos, label, color) = {
        rect(a, b, fill: color.transparentize(75%), stroke: none)
        content(pos, text(fill: color, label))
      }
      region((-4, 0), (4, 2), (-3, 1.3), $P_1$, rgb(65, 105, 225))
      region((-4, -2), (0, 0), (-3, -1.4), $P_2$, rgb(34, 139, 34))
      region((0, -2), (4, 0), (3, -1.4), $P_3$, rgb(205, 110, 40))
      set-style(stroke: (paint: ink, thickness: 1.2pt))
      line((-4, 0), (4, 0))
      line((0, -2), (0, 0))
      content((3.0, 0.25), text(fill: ink, $y = 0$), anchor: "west")
    })

    #figure(
      context if target() == "html" { html.frame(non-voronoi) } else { non-voronoi },
      caption: [Voronoi 領域として表現できない多面体分割],
    )

    そして点 $p_1 = (x_1, y_1)^T in P_1$, $p_2 = (x_2, y_2)^T in P_2$, $p_3 = (x_3, y_3)^T in P_3$ が存在して
    $
      P_k = {p in RR^2 mid(|) norm(p - p_k) <= norm(p - p_i), space i eq.not k}
    $
    であるとする.

    このとき $(x, 0)^T in P_1$ であることから
    $
      norm((x, 0)^T - p_1) & <= norm((x, 0)^T - p_2) \
       (x - x_1)^2 + y_1^2 & <= (x - x_2)^2 + y_2^2 \
           2 (x_2 - x_1) x & <= y_2^2 - y_1^2 + x_2^2 - x_1^2.
    $
    ここで左辺は $x$ に依存するが右辺は定数である.
    $(x_2 - x_1) > 0$ のとき $x$ を正に十分大きく取ることで矛盾し,
    $(x_2 - x_1) < 0$ のとき $x$ を負に十分大きく取ることで矛盾する.
    従って $x_2 = x_1$ である.
    同様の議論で $x_3 = x_1$ もわかる.
    $p_2 in P_2$ かつ $p_3 in P_3$ であるため $x_2 <= 0 <= x_3$ であり, 従って $x_1 = x_2 = x_3 = 0$ である.

    また, $(0, y)^T in P_2 inter P_3$ より
    $
      norm((0, y)^T - p_2) & = norm((0, y)^T - p_3) \
               (y - y_2)^2 & = (y - y_3)^2 \
           2 (y_3 - y_2) y & = y_3^2 - y_2^2
    $
    ここで右辺は定数であるため $y_2 = y_3$ であるとわかる.

    従って $p_2 = p_3$ であるが,
    $P_2 without P_3$ は空ではないため $norm(p - p_2) < norm(p - p_3)$ となる $p$ が存在することになり矛盾する. $qed$
  ],
)
