#import "../../lib.typ": alpha-enum, ex

#let int = math.op("int")

== Exercise 2.9 (Voronoi sets and polyhedral decomposition)

#ex[
  Let $x_0, dots, x_K in RR^n$ be distinct. Consider the set of points that are
  closer (in Euclidean norm) to $x_0$ than the other $x_i$, i.e.,

  $ V = { x in RR^n mid(|) norm(x - x_0)_2 <= norm(x - x_i)_2, i = 1, dots, K }. $

  $V$ is called the Voronoi region around $x_0$ with respect to $x_1, dots, x_K$.

  #alpha-enum(
    [
      Show that $V$ is a polyhedron. Express $V$ in the form $V = { x mid(|) A x prec.eq b }$.
    ],
    [
      Conversely, given a polyhedron $P$ with nonempty interior, show how to find
      $x_0, dots, x_K$ so that the polyhedron is the Voronoi region of $x_0$ with
      respect to $x_1, dots, x_K$.
    ],
    [
      We can also consider the sets

      $ V_k = { x in RR^n mid(|) norm(x - x_k)_2 <= norm(x - x_i)_2, i eq.not k }. $

      The set $V_k$ consists of points in $RR^n$ for which the closest point in the
      set ${x_0, dots, x_K}$ is $x_k$. \
      The sets $V_0, dots, V_K$ give a #emph[polyhedral decomposition] of $RR^n$.
      More precisely, the sets $V_k$ are polyhedra with nonempty interior,
      $union.big_(k=0)^K V_k = RR^n$, and $"int" V_i inter "int" V_j = nothing$ for
      $i eq.not j$, i.e., $V_i$ and $V_j$ intersect at most along a boundary. \
      Suppose that $P_1, dots, P_m$ are polyhedra with nonempty interior such that
      $union.big_(i=1)^m P_i = RR^n$, $"int" P_i inter "int" P_j = nothing$ for
      $i eq.not j$. Can this polyhedral decomposition of $RR^n$ be described as the
      Voronoi regions generated by an appropriate set of points?
    ],
  )
]

*解答*:
#alpha-enum(
  [
    $A in RR^(K times n)$ と $b in RR^K$ を次のように定める.

    $
      A = mat((x_1 - x_0)^T; dots.v; (x_K - x_0)^T), quad b = mat((norm(x_1)_2^2 - norm(x_0)_2^2) / 2; dots.v; (norm(x_K)_2^2 - norm(x_0)_2^2) / 2)
    $

    このとき #link(<ex-2-7>)[演習問題 2.7] より

    $
      { x mid(|) A x prec.eq b } = { x in RR^n mid(|) norm(x - x_0)_2 <= norm(x - x_i)_2, i = 1, dots, K } = V
    $

    である.
  ],
  [
    $P$ は内部を持つため $P = { x in RR^n mid(|) A x prec.eq b}$ と書ける ($A in RR^(K times n)$, $b in RR^K$).
    $A$ の $i$ 行目を $a_i^T$ とおく.
    ここで $A$ は全ての成分が $0$ の行を持たないとする. つまり $a_i eq.not 0$ である.
    $x_0 in int P$ を取る. このとき $A x_0 prec b$ が成り立つ.
    $t_i$ と $x_i$ を以下のように定める.

    $
      t_i := (b_i - a_i^T x_0) / norm(a_i)_2^2, quad x_i := x_0 + 2 t_i a_i
    $

    ここで $x_i$ は超平面 $a_i x = b_i$ における $x_0$ の鏡映となっている.
    また, $t_i > 0$ であることに注意する.
    このとき

    $
      a_i^T y <= b_i & <=> 2 t_i a_i^T y <= 2 t_i b_i \
                     & <=> (x_i - x_0)^T y <= 2 t_i (t_i norm(a_i)_2^2 + a_i^T x_0) \
                     & <=> (x_i - x_0)^T y <= 1/2 (4 norm(t_i a_i)_2^2 + 4 t_i a_i^T x_0) \
                     & <=> (x_i - x_0)^T y <= (norm(x_i)_2^2 - norm(x_0)_2^2)/2.
    $

    従って $P$ は $x_1, dots, x_K$ に対する $x_0$ の Voronoi region である. $qed$
  ],
  [
    WIP
  ],
)
